### ISSUE TITLE
(readonly) xfcr | todo

### ISSUE THREAD

**Issue by sh1kxrv** [xafxafxaf/xaf-crate-reborn#1]
## ToDo:
- [ ] **Рефакторинг всего приложения** -> ts-refactor branch
   - [ ] Разделение пакетов на самостоятельные репозитории
- [x] Создать более гибкую версию сборки шаблонов
  - [ ] (CHECK:) Возможно ли добавлять свои шаблоны юзерам и после взаимодействовать с ними
  - [x] Декларативный подход ( .json файлы около шаблона с конфигурацией )
- [x] Система модификаций ( интеграция husky/jest/etc в определенный шаблон )
  - [x] `project.options.json` - `entries`
  - [x] Отслеживание конфликтов модификаций
- [x] ~Перенос Swagger-Codegen ( OpenAPI + Swagger )~ -> [Migrated](https://github.com/xafxafxaf/xaf-vault)
- [ ] Перенос интеграций платформ ( отныне модификации могут и в интеграции платформ )
  - [ ] Electron
  - [ ] Capacitor
  - [ ] Tauri
- [x] Перенос шаблонов
  - [x] Express
    - [x] Sequalize ORM
  - [x] ESBuild
  - [x] Vue3
    - [x] Migrate to Pinia from Vuex
    - [x] Переписать систему Middleware
      - [ ] Добавить приоритетность ( возможно сделать с помощью LinkedList )
  - [ ] Monorepo + Shared-library
    - [ ] Lerna
    - [ ] Turbo
- [ ] Перенос Crate'а tools
  - [x] ~index.js | Generator~ -> [Migrated](https://github.com/xafxafxaf/index-gen-ext)
  - [ ] Информация о проекте
    - [ ] Установленные модификации
    - [ ] Наименование
    - [ ] Дата создания
- [ ] Локальное создание своих шаблонов для дальнейшего использования
  - [ ] (+) Github Templates ?
- [ ] Проверка обновлений xfcr
- [ ] Vue Template Update
  - [ ] Modal's -> modal provide/inject
  - [ ] Font's
